### ISSUE TITLE
Considering \n possibility in proposition's node

### ISSUE THREAD

**Issue by ravikiranrao** [csl-622/metamath#2]
While constructing a new node using the pattern, like [Prop 1.13], consider \n possibility. Ignoring this fact has resulted in not putting an edge between few theorems.

**Comment by ravikiranrao** [comment]
Close this if it is done.

**Comment by ravikiranrao** [comment]
The in-degree of 2.14 is 5, according to the text book. But the code says it is 4; it is not considering the \n case.

**Comment by codewithrish** [comment]
But we replaced \n with '' empty string

**Comment by ravikiranrao** [comment]
It is neither working with /r/n nor with just /r. Browse the internet and debug it.
